# Generated by Django 3.0.7 on 2020-07-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('SW', '소프트웨어 융합대학'), ('NS', '자연과학대학')], default='SW', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Subscribe',
            },
        ),
    ]
