# Generated by Django 3.0.7 on 2020-07-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='topic',
            field=models.CharField(choices=[('SW', '소프트웨어 융합대학'), ('NS', '자연과학대학')], default='SW', max_length=10, unique=True),
        ),
    ]
