# Generated by Django 3.0.7 on 2020-07-09 11:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20200709_1110'),
        ('subscribe_app', '0002_auto_20200708_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='topic',
            field=models.CharField(choices=[('SW', '소프트웨어 융합대학'), ('NS', '자연과학대학')], default='SW', max_length=10),
        ),
    ]
