# Generated by Django 3.0.7 on 2020-07-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_app', '0003_auto_20200709_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='topic',
            field=models.CharField(choices=[('Software engineering', '소프트웨어 융합대학'), ('Natural science', '자연과학대학')], default='Software engineering', max_length=20),
        ),
    ]
