# Generated by Django 3.0.7 on 2020-07-10 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20200709_1110'),
        ('subscribe_app', '0005_auto_20200709_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={},
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='user',
        ),
        migrations.CreateModel(
            name='Auth_Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe_app.Subscribe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.User')),
            ],
            options={
                'verbose_name_plural': 'Auth_Subscribe',
            },
        ),
    ]
