# Generated by Django 3.0.7 on 2020-07-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
                ('done_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'CrawlerTask',
            },
        ),
    ]
