# Generated by Django 3.0.7 on 2020-07-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawlertask',
            options={'ordering': ['done_at'], 'verbose_name_plural': 'CrawlerTask'},
        ),
    ]
