# Generated by Django 3.0.7 on 2020-06-30 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name_plural': 'Url'},
        ),
        migrations.AddField(
            model_name='posts',
            name='url',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='board_app.Url'),
        ),
    ]
