# Generated by Django 3.0.7 on 2020-07-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_auto_20200630_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['updated_at'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name_plural': 'Urls'},
        ),
    ]
