# Generated by Django 3.0.7 on 2020-07-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20200709_1110'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auth',
            managers=[
            ],
        ),
    ]
